version: '2'

services:

  frontend:
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    ports:
      - 80:80

  oracle:
    build:
      context: ./bdb-hyperledger-oracle
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    environment:
      - HOST_REDIS=redis
      - DEBUG=log
    depends_on:
      - redis
    command: npm run start

  redis:
    image: redis:alpine
    ports:
      - "6379"
    command: redis-server --save "" --appendonly no